# =============== BASE IMAGE ===============
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# The real OpenAI key comes from ENV in docker-compose
ENV OPENAI_API_KEY=""
ENV CLASSIFIER_THRESHOLD=""
ENV CLASSIFIER_MODEL_VERSION=""
ENV ML_CLASSIFIER_ACCURACY_TARGET=""
ENV ML_CLASSIFIER_EXPERIMENT_NAME=""
ENV ML_CLASSIFIER_TFIDF_MAX_FEATURES=""

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# server execution FastAPI (Uvicorn)
CMD ["uvicorn", "apps.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
